# Entry point
---

- name: Collecting facts
  hosts: all
  gather_facts: yes

# - name: some tests
#   hosts: all
#   tasks:
#    - shell: /usr/bin/uptime
#      register: result

#    - debug: var=result

#    - name: test
#      shell: echo test

# Play role(s) for all hosts in s3it-playbooks/<group>.yml (see hosts for groups)
- include: s3it-playbooks/storage_servers.yml
# - include: s3it-playbooks/samba_servers.yml
