- src: debops.ansible
- src: debops.apt
- src: debops.apt_preferences
- src: debops.auth
- src: debops.backporter
- src: debops.boxbackup
- src: debops.console
- src: debops.debops
- src: debops.debug
- src: debops.dhcpd
- src: debops.directories
- src: debops.dnsmasq
- src: debops.dokuwiki
- src: debops.dovecot
- src: debops.elasticsearch
- src: debops.encfs
- src: debops.etc_services
- src: debops.etherpad
- src: debops.fail2ban
- src: debops.ferm
- src: debops.gitlab
- src: debops.gitlab_ci
- src: debops.gitlab_ci_runner
- src: debops.gitusers
- src: debops.golang
- src: debops.hwraid
- src: debops.ifupdown
- src: debops.ipxe
- src: debops.java
- src: debops.kvm
- src: debops.lxc
- src: debops.mailman
- src: debops.monit
- src: debops.monkeysphere
- src: debops.mysql
- src: debops.nfs
- src: debops.nginx
- src: debops.nodejs
- src: debops.ntp
- src: debops.openvz
- src: debops.owncloud
- src: debops.php5
- src: debops.phpipam
- src: debops.phpmyadmin
- src: debops.pki
- src: debops.postfix
- src: debops.postgresql
- src: debops.preseed
- src: debops.radvd
- src: debops.rails_deploy
- src: debops.redis
- src: debops.reprepro
- src: debops.rsnapshot
- src: debops.rsyslog
- src: debops.ruby
- src: debops.safekeep
- src: debops.salt
- src: debops.samba
- src: debops.secret
- src: debops.sftpusers
- src: debops.sks
- src: debops.slapd
- src: debops.smstools
- src: debops.sshd
- src: debops.sshkeys
- src: debops.stunnel
- src: debops.subnetwork
- src: debops.tcpwrappers
- src: debops.tftpd
- src: debops.tgt
- src: debops.users
